[package]
name = "build-macros"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
build-tool = { path = "../build-tool" }
md-5 = { version = "0.10.5", default-features = false }
object = "0.30.3"
syn = "2.0.0"
zstd = "0.12.3"
